development:
  adapter: postgresql
  database: openstreetmap
  username: openstreetmap
  password: openstreetmap
  host: localhost
  port: 5433
  encoding: utf8

test:
  adapter: postgresql
  database: osm_test
  username: openstreetmap
  password: openstreetmap
  host: localhost
  port: 5433
  encoding: utf8

production:
  adapter: postgresql
  database: openstreetmap
  username: openstreetmap
  password: openstreetmap
  host: localhost
  port: 5433
  encoding: utf8
